package wire

import (
	"context"
	"net"
	"net/http"
	"time"

	"connectrpc.com/connect"

	"github.com/excavador/locksmith/pkg/gen/gpgsmith/v1/gpgsmithv1connect"
)

// Client is the typed gpgsmith ConnectRPC client. It bundles all eight
// generated service clients into one struct so callers (CLI commands, web
// UI shim, TUI) only have one thing to import and one connection lifetime
// to manage.
//
// A Client is constructed via:
//
//   - NewUnixSocketClient(socketPath)  for talking to a daemon over Unix domain socket
//   - NewHTTPClient(httpClient, baseURL) for talking to any Connect endpoint
//
// The exposed sub-clients (Daemon, Vault, Key, ...) are the generated
// interfaces. Calls take typed proto messages; the Connect transport handles
// (de)serialization. Callers in pkg/cli/gpgsmith and pkg/webui/gpgsmith
// translate between proto types and CLI/HTML data on their side of the wire.
type (
	Client struct {
		httpClient *http.Client
		baseURL    string

		Daemon   gpgsmithv1connect.DaemonServiceClient
		Vault    gpgsmithv1connect.VaultServiceClient
		Key      gpgsmithv1connect.KeyServiceClient
		Identity gpgsmithv1connect.IdentityServiceClient
		Card     gpgsmithv1connect.CardServiceClient
		Server   gpgsmithv1connect.ServerServiceClient
		Audit    gpgsmithv1connect.AuditServiceClient
		Event    gpgsmithv1connect.EventServiceClient
	}
)

// NewUnixSocketClient builds a Client that talks to a Connect server over
// a Unix domain socket at the given path. This is the production
// configuration the CLI uses to talk to the daemon.
//
// The HTTP base URL is "http://unix" — a synthetic placeholder; Connect
// uses the http.Client's transport for the actual dial, so the host
// portion is never resolved. The path portion of every Connect request
// is the gRPC method path generated by buf+protoc-gen-connect-go.
func NewUnixSocketClient(socketPath string) *Client {
	hc := &http.Client{
		Transport: &http.Transport{
			DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
				var d net.Dialer
				return d.DialContext(ctx, "unix", socketPath)
			},
			// We're talking to a long-lived process over a local socket;
			// connection reuse is essentially free.
			MaxIdleConns:    8,
			IdleConnTimeout: 90 * time.Second,
		},
	}
	// Production CLI client: every outbound call carries the current
	// GPGSMITH_SESSION env var as a Gpgsmith-Session header (no-op when
	// unset). Tests that construct a Client directly via NewHTTPClient
	// without this option get a bare connection with no auto-stamping.
	return NewHTTPClient(hc, "http://unix", WithEnvSessionInterceptor())
}

// NewHTTPClient builds a Client around an arbitrary http.Client and base
// URL. Used by tests (httptest.Server provides both) and could be used by
// other transports in the future.
func NewHTTPClient(hc *http.Client, baseURL string, opts ...connect.ClientOption) *Client {
	return &Client{
		httpClient: hc,
		baseURL:    baseURL,
		Daemon:     gpgsmithv1connect.NewDaemonServiceClient(hc, baseURL, opts...),
		Vault:      gpgsmithv1connect.NewVaultServiceClient(hc, baseURL, opts...),
		Key:        gpgsmithv1connect.NewKeyServiceClient(hc, baseURL, opts...),
		Identity:   gpgsmithv1connect.NewIdentityServiceClient(hc, baseURL, opts...),
		Card:       gpgsmithv1connect.NewCardServiceClient(hc, baseURL, opts...),
		Server:     gpgsmithv1connect.NewServerServiceClient(hc, baseURL, opts...),
		Audit:      gpgsmithv1connect.NewAuditServiceClient(hc, baseURL, opts...),
		Event:      gpgsmithv1connect.NewEventServiceClient(hc, baseURL, opts...),
	}
}

// Close releases idle HTTP connections. Safe to call multiple times.
func (c *Client) Close() {
	if c == nil || c.httpClient == nil {
		return
	}
	if t, ok := c.httpClient.Transport.(*http.Transport); ok {
		t.CloseIdleConnections()
	}
}
