name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: true

      - name: Tidy & format check
        run: devbox run -- just tidy-check

      - name: All (deps + fmt + lint + test + build)
        run: devbox run -- just all
